build:
  tests:
    override:
      -
        command: phpunit --coverage-clover=build/clover.xml
        coverage:
          file: build/clover.xml
          format: php-clover

filter:
  excluded_paths:
    - "Test/"               # Everything in a root level "tests" directory
    - "Tests/"              # Without trailing "/", just ignores a single file name "tests"
